// Builds the editor palette from a Qlippoth Station game checkout.
//
//   npm run palette                      game checkout next to this repository (see game-dir.mjs)
//   npm run palette -- --game <path>     any other checkout
//
// Output (git-ignored, regenerated by CI):
//   public/palette/palette.json   ids, names, layers, atlas coordinates
//   public/palette/atlas.png      one 32x32 icon per palette entry
//   public/palette/credits.json   license/copyright of every sprite used
//
// Only what the editor needs is read: tile prototypes and entity prototypes with a sprite.
// Inheritance is resolved field by field per component, which is close enough to the game for icons.

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import YAML from "yaml";
import { PNG } from "pngjs";
import { EDITOR_ROOT, findGame } from "./game-dir.mjs";

const ICON = 32;
const OUT_DIR = path.join(EDITOR_ROOT, "public/palette");

// Which entity folders go to which editor layer. First match wins; anything else is skipped.
const ENTITY_LAYERS = [
  { prefix: "Structures/Walls", layer: "structure" },
  { prefix: "Structures/Doors", layer: "structure" },
  { prefix: "Structures/Windows", layer: "structure" },
  { prefix: "Structures/", layer: "object" },
  { prefix: "Objects/", layer: "object" },
  { prefix: "Qlippoths/", layer: "object" },
];

// Entities in these categories never show up in the in-game spawn menu, so they are left out here too.
const HIDDEN_CATEGORIES = new Set(["HideSpawnMenu", "DoNotMap", "Debug"]);

function walk(dir, ext) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(full, ext));
    else if (entry.name.endsWith(ext)) files.push(full);
  }
  return files;
}

function toPosix(p) {
  return p.split(path.sep).join("/");
}

const unreadable = [];

function readYamlDocs(file) {
  // Game YAML uses custom tags (!type:Foo). They are irrelevant for icons, so they are parsed as plain values.
  // Some files start with a BOM, which the parser does not accept.
  const text = fs.readFileSync(file, "utf8").replace(/^﻿/, "");
  try {
    const doc = YAML.parse(text, { logLevel: "silent", uniqueKeys: false });
    return Array.isArray(doc) ? doc : [];
  } catch {
    unreadable.push(file);
    return [];
  }
}

function readLocale(resources) {
  const strings = new Map();
  const dir = path.join(resources, "Locale", "en-US");
  if (!fs.existsSync(dir)) return strings;
  for (const file of walk(dir, ".ftl")) {
    for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
      const match = /^([a-zA-Z0-9_-]+)\s*=\s*(.+)$/.exec(line);
      if (match && !match[2].includes("{")) strings.set(match[1], match[2].trim());
    }
  }
  return strings;
}

function parents(proto) {
  if (!proto.parent) return [];
  return Array.isArray(proto.parent) ? proto.parent : [proto.parent];
}

// ---- Tiles --------------------------------------------------------------------------------------

function collectTiles(resources, locale) {
  const byId = new Map();
  for (const file of walk(path.join(resources, "Prototypes", "Tiles"), ".yml")) {
    for (const proto of readYamlDocs(file)) {
      if (proto?.type === "tile" && proto.id) byId.set(proto.id, proto);
    }
  }

  const resolve = (id, seen = new Set()) => {
    const proto = byId.get(id);
    if (!proto || seen.has(id)) return {};
    seen.add(id);
    const merged = {};
    for (const parent of parents(proto)) Object.assign(merged, resolve(parent, seen));
    const { abstract, parent, ...own } = proto;
    return Object.assign(merged, own);
  };

  const tiles = [];
  for (const [id, proto] of byId) {
    if (proto.abstract) continue;
    const tile = resolve(id);
    if (!tile.sprite) continue;
    tiles.push({
      id,
      name: locale.get(tile.name) ?? tile.name ?? id,
      category: tile.isSubfloor ? "Subfloor" : "Floor",
      image: path.join(resources, tile.sprite.replace(/^\//, "")),
    });
  }
  return tiles;
}

// ---- Entities -----------------------------------------------------------------------------------

function collectEntities(resources) {
  const entityRoot = path.join(resources, "Prototypes", "Entities");
  const byId = new Map();
  for (const file of walk(entityRoot, ".yml")) {
    const relative = toPosix(path.relative(entityRoot, file));
    for (const proto of readYamlDocs(file)) {
      if (proto?.type === "entity" && proto.id) byId.set(proto.id, { proto, relative });
    }
  }

  const cache = new Map();
  const resolve = (id, seen = new Set()) => {
    if (cache.has(id)) return cache.get(id);
    const entry = byId.get(id);
    if (!entry || seen.has(id)) return { components: {} };
    seen.add(id);

    const result = { components: {} };
    for (const parent of parents(entry.proto)) {
      const inherited = resolve(parent, seen);
      result.name ??= inherited.name;
      result.suffix ??= inherited.suffix;
      for (const [type, fields] of Object.entries(inherited.components)) {
        result.components[type] = { ...result.components[type], ...fields };
      }
    }
    if (entry.proto.name) result.name = entry.proto.name;
    if (entry.proto.suffix) result.suffix = entry.proto.suffix;
    for (const component of entry.proto.components ?? []) {
      if (!component?.type) continue;
      const { type, ...fields } = component;
      result.components[type] = { ...result.components[type], ...fields };
    }
    cache.set(id, result);
    return result;
  };

  const entities = [];
  for (const [id, { proto, relative }] of byId) {
    if (proto.abstract) continue;
    if ((proto.categories ?? []).some((category) => HIDDEN_CATEGORIES.has(category))) continue;
    const mapping = ENTITY_LAYERS.find((rule) => relative.startsWith(rule.prefix));
    if (!mapping) continue;

    const resolved = resolve(id);
    const icon = findIcon(resources, resolved.components);
    if (!icon) continue;

    const folders = relative.split("/");
    entities.push({
      id,
      name: resolved.suffix ? `${resolved.name ?? id} (${resolved.suffix})` : resolved.name ?? id,
      layer: mapping.layer,
      category: folders.slice(0, Math.min(2, folders.length - 1)).join("/"),
      ...icon,
    });
  }
  return entities;
}

// Icon component wins over Sprite; a state that is missing falls back to the first layer, then to the first RSI state.
function findIcon(resources, components) {
  const icon = components.Icon ?? {};
  const sprite = components.Sprite ?? {};
  const firstLayer = (sprite.layers ?? []).find((layer) => layer && (layer.state || layer.sprite)) ?? {};

  const rsi = icon.sprite ?? sprite.sprite ?? firstLayer.sprite;
  if (!rsi) return null;
  const rsiDir = path.join(resources, "Textures", rsi);
  const metaFile = path.join(rsiDir, "meta.json");
  if (!fs.existsSync(metaFile)) return null;

  const meta = JSON.parse(fs.readFileSync(metaFile, "utf8").replace(/^﻿/, ""));
  const states = (meta.states ?? []).map((state) => state.name);
  let state = icon.state ?? sprite.state ?? firstLayer.state;
  if (!state || !states.includes(state)) state = states[0];
  if (!state) return null;

  const image = path.join(rsiDir, `${state}.png`);
  if (!fs.existsSync(image)) return null;
  return {
    image,
    frame: meta.size ?? { x: ICON, y: ICON },
    credit: { source: toPosix(path.join("Textures", rsi)), license: meta.license, copyright: meta.copyright },
  };
}

// ---- Tile credits -------------------------------------------------------------------------------

function tileCredits(resources) {
  const credits = new Map();
  const file = path.join(resources, "Textures", "Tiles", "attributions.yml");
  if (!fs.existsSync(file)) return credits;
  for (const entry of readYamlDocs(file)) {
    for (const name of entry?.files ?? []) {
      credits.set(name, { license: entry.license, copyright: entry.copyright });
    }
  }
  return credits;
}

// ---- Atlas --------------------------------------------------------------------------------------

function buildAtlas(items) {
  const columns = Math.max(1, Math.ceil(Math.sqrt(items.length)));
  const rows = Math.max(1, Math.ceil(items.length / columns));
  const atlas = new PNG({ width: columns * ICON, height: rows * ICON });
  const placed = [];
  const pngCache = new Map();

  for (const item of items) {
    let source = pngCache.get(item.image);
    if (source === undefined) {
      try {
        source = PNG.sync.read(fs.readFileSync(item.image));
      } catch {
        source = null;
      }
      pngCache.set(item.image, source);
    }
    if (!source) continue;

    const index = placed.length;
    const ax = (index % columns) * ICON;
    const ay = Math.floor(index / columns) * ICON;
    // First frame (south direction, frame 0) is the top-left cell of the sheet.
    const fw = Math.min(item.frame?.x ?? ICON, source.width);
    const fh = Math.min(item.frame?.y ?? ICON, source.height);
    blitScaled(source, fw, fh, atlas, ax, ay);

    const { image, frame, ...rest } = item;
    placed.push({ ...rest, icon: index });
  }
  return { atlas, columns, placed };
}

// Nearest-neighbour fit of the frame into a 32x32 cell, keeping aspect ratio and centering it.
function blitScaled(source, fw, fh, target, tx, ty) {
  const scale = Math.min(1, ICON / fw, ICON / fh);
  const dw = Math.max(1, Math.round(fw * scale));
  const dh = Math.max(1, Math.round(fh * scale));
  const ox = tx + Math.floor((ICON - dw) / 2);
  const oy = ty + Math.floor((ICON - dh) / 2);
  for (let y = 0; y < dh; y++) {
    for (let x = 0; x < dw; x++) {
      const sx = Math.min(fw - 1, Math.floor(x / scale));
      const sy = Math.min(fh - 1, Math.floor(y / scale));
      const si = (sy * source.width + sx) << 2;
      const di = ((oy + y) * target.width + (ox + x)) << 2;
      source.data.copy(target.data, di, si, si + 4);
    }
  }
}

function gameCommit(game) {
  try {
    return execSync("git rev-parse HEAD", { cwd: game, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return null;
  }
}

// ---- Main ---------------------------------------------------------------------------------------

const { game, resources } = findGame();
const locale = readLocale(resources);
const tileCreditMap = tileCredits(resources);

const tiles = collectTiles(resources, locale).map((tile) => ({
  ...tile,
  layer: "floor",
  credit: {
    source: toPosix(path.relative(resources, tile.image)),
    ...(tileCreditMap.get(path.basename(tile.image)) ?? {}),
  },
}));
const entities = collectEntities(resources);

const sortKey = (a, b) => a.layer.localeCompare(b.layer) || a.category.localeCompare(b.category) || a.name.localeCompare(b.name);
const { atlas, columns, placed } = buildAtlas([...tiles, ...entities].sort(sortKey));

const credits = new Map();
for (const item of placed) {
  if (item.credit?.source) credits.set(item.credit.source, item.credit);
}

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, "atlas.png"), PNG.sync.write(atlas));
fs.writeFileSync(
  path.join(OUT_DIR, "palette.json"),
  JSON.stringify({
    version: 1,
    gameCommit: gameCommit(game),
    iconSize: ICON,
    atlasColumns: columns,
    items: placed.map(({ credit, ...item }) => item),
  })
);
fs.writeFileSync(
  path.join(OUT_DIR, "credits.json"),
  JSON.stringify([...credits.values()].sort((a, b) => a.source.localeCompare(b.source)), null, 1)
);

for (const file of unreadable) console.warn(`Skipped unreadable YAML: ${toPosix(path.relative(game, file))}`);
const count = (layer) => placed.filter((item) => item.layer === layer).length;
console.log(`Palette: ${count("floor")} tiles, ${count("structure")} structures, ${count("object")} objects -> ${toPosix(path.relative(process.cwd(), OUT_DIR))}`);
